name: Move New Issue to issue:Todo

on:
  issues:
    types:
      - opened

jobs:
  move_issue_to_do:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "issue:Todo"
        uses: actions/add-to-project@v0.4.0
        with:
          project_url: https://github.com/KaitoMizuuchi/projects/4
          column_name: "issue:Todo"
          github_token: ${{ secrets.GITHUB_TOKEN }}
