name: Move New Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  move_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Project
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/KaitoMizuuchi/projects/4
          github-token: ${{ secrets.GITHUB_TOKEN }}


